CREATE TABLE IF NOT EXISTS echo_message (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    message VARCHAR(1024) NOT NULL,
    length INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

